/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.employeemanagement.hrdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class UserNameCountResponse implements Serializable {


    @ColumnAlias("USERNAME_COUNT")
    private BigInteger usernameCount;

    public BigInteger getUsernameCount() {
        return this.usernameCount;
    }

    public void setUsernameCount(BigInteger usernameCount) {
        this.usernameCount = usernameCount;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UserNameCountResponse)) return false;
        final UserNameCountResponse userNameCountResponse = (UserNameCountResponse) o;
        return Objects.equals(getUsernameCount(), userNameCountResponse.getUsernameCount());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getUsernameCount());
    }
}